import scrapy


class BuaaUrlSpider(scrapy.Spider):
    name = "buaa_url"
    def start_requests(self):
        self.file = open("url.txt", 'a')
        header='http://teacher.buaa.edu.cn/pylb.jsp?totalpage='
        tail='&wbtreeid=1001&lang=zh_CN'
        urls = [
            '2&PAGENUM=1&urltype=tsites.PinYinTeacherList&py=b',
            '2&PAGENUM=2&urltype=tsites.PinYinTeacherList&py=b',
            '5&PAGENUM=1&urltype=tsites.PinYinTeacherList&py=c',
            '5&PAGENUM=2&urltype=tsites.PinYinTeacherList&py=c',
            '5&PAGENUM=3&urltype=tsites.PinYinTeacherList&py=c',
            '5&PAGENUM=4&urltype=tsites.PinYinTeacherList&py=c',
            '5&PAGENUM=5&urltype=tsites.PinYinTeacherList&py=c',
            '4&PAGENUM=1&urltype=tsites.PinYinTeacherList&py=d',
            '4&PAGENUM=2&urltype=tsites.PinYinTeacherList&py=d',
            '4&PAGENUM=3&urltype=tsites.PinYinTeacherList&py=d',
            '4&PAGENUM=4&urltype=tsites.PinYinTeacherList&py=d',
            '2&PAGENUM=1&urltype=tsites.PinYinTeacherList&py=f',
            '2&PAGENUM=2&urltype=tsites.PinYinTeacherList&py=f',
            '4&PAGENUM=1&urltype=tsites.PinYinTeacherList&py=g',
            '4&PAGENUM=2&urltype=tsites.PinYinTeacherList&py=g',
            '4&PAGENUM=3&urltype=tsites.PinYinTeacherList&py=g',
            '4&PAGENUM=4&urltype=tsites.PinYinTeacherList&py=g',
            '6&PAGENUM=1&urltype=tsites.PinYinTeacherList&py=h',
            '6&PAGENUM=2&urltype=tsites.PinYinTeacherList&py=h',
            '6&PAGENUM=3&urltype=tsites.PinYinTeacherList&py=h',
            '6&PAGENUM=4&urltype=tsites.PinYinTeacherList&py=h',
            '6&PAGENUM=5&urltype=tsites.PinYinTeacherList&py=h',
            '6&PAGENUM=6&urltype=tsites.PinYinTeacherList&py=h',
            '3&PAGENUM=1&urltype=tsites.PinYinTeacherList&py=j',
            '3&PAGENUM=2&urltype=tsites.PinYinTeacherList&py=j',
            '3&PAGENUM=3&urltype=tsites.PinYinTeacherList&py=j',
            '1&PAGENUM=1&urltype=tsites.PinYinTeacherList&py=k',
            '16&PAGENUM=1&urltype=tsites.PinYinTeacherList&py=l',
            '16&PAGENUM=2&urltype=tsites.PinYinTeacherList&py=l',
            '16&PAGENUM=3&urltype=tsites.PinYinTeacherList&py=l',
            '16&PAGENUM=4&urltype=tsites.PinYinTeacherList&py=l',
            '16&PAGENUM=5&urltype=tsites.PinYinTeacherList&py=l',
            '16&PAGENUM=6&urltype=tsites.PinYinTeacherList&py=l',
            '16&PAGENUM=7&urltype=tsites.PinYinTeacherList&py=l',
            '16&PAGENUM=8&urltype=tsites.PinYinTeacherList&py=l',
            '16&PAGENUM=9&urltype=tsites.PinYinTeacherList&py=l',
            '16&PAGENUM=10&urltype=tsites.PinYinTeacherList&py=l',
            '16&PAGENUM=11&urltype=tsites.PinYinTeacherList&py=l',
            '16&PAGENUM=12&urltype=tsites.PinYinTeacherList&py=l',
            '16&PAGENUM=13&urltype=tsites.PinYinTeacherList&py=l',
            '16&PAGENUM=14&urltype=tsites.PinYinTeacherList&py=l',
            '16&PAGENUM=15&urltype=tsites.PinYinTeacherList&py=l',
            '16&PAGENUM=16&urltype=tsites.PinYinTeacherList&py=l',
            '3&PAGENUM=1&urltype=tsites.PinYinTeacherList&py=m',
            '3&PAGENUM=2&urltype=tsites.PinYinTeacherList&py=m',
            '3&PAGENUM=3&urltype=tsites.PinYinTeacherList&py=m',
            '1&PAGENUM=1&urltype=tsites.PinYinTeacherList&py=n',
            '2&PAGENUM=1&urltype=tsites.PinYinTeacherList&py=p',
            '2&PAGENUM=2&urltype=tsites.PinYinTeacherList&py=p',
            '2&PAGENUM=1&urltype=tsites.PinYinTeacherList&py=q',
            '2&PAGENUM=2&urltype=tsites.PinYinTeacherList&py=q',
            '1&PAGENUM=1&urltype=tsites.PinYinTeacherList&py=r',
            '6&PAGENUM=1&urltype=tsites.PinYinTeacherList&py=s',
            '6&PAGENUM=2&urltype=tsites.PinYinTeacherList&py=s',
            '6&PAGENUM=3&urltype=tsites.PinYinTeacherList&py=s',
            '6&PAGENUM=4&urltype=tsites.PinYinTeacherList&py=s',
            '6&PAGENUM=5&urltype=tsites.PinYinTeacherList&py=s',
            '6&PAGENUM=6&urltype=tsites.PinYinTeacherList&py=s',
            '2&PAGENUM=1&urltype=tsites.PinYinTeacherList&py=t',
            '2&PAGENUM=2&urltype=tsites.PinYinTeacherList&py=t',
            '13&PAGENUM=1&urltype=tsites.PinYinTeacherList&py=w',
            '13&PAGENUM=2&urltype=tsites.PinYinTeacherList&py=w',
            '13&PAGENUM=3&urltype=tsites.PinYinTeacherList&py=w',
            '13&PAGENUM=4&urltype=tsites.PinYinTeacherList&py=w',
            '13&PAGENUM=5&urltype=tsites.PinYinTeacherList&py=w',
            '13&PAGENUM=6&urltype=tsites.PinYinTeacherList&py=w',
            '13&PAGENUM=7&urltype=tsites.PinYinTeacherList&py=w',
            '13&PAGENUM=8&urltype=tsites.PinYinTeacherList&py=w',
            '13&PAGENUM=9&urltype=tsites.PinYinTeacherList&py=w',
            '13&PAGENUM=10&urltype=tsites.PinYinTeacherList&py=w',
            '13&PAGENUM=11&urltype=tsites.PinYinTeacherList&py=w',
            '13&PAGENUM=12&urltype=tsites.PinYinTeacherList&py=w',
            '13&PAGENUM=13&urltype=tsites.PinYinTeacherList&py=w',
            '5&PAGENUM=1&urltype=tsites.PinYinTeacherList&py=x',
            '5&PAGENUM=2&urltype=tsites.PinYinTeacherList&py=x',
            '5&PAGENUM=3&urltype=tsites.PinYinTeacherList&py=x',
            '5&PAGENUM=4&urltype=tsites.PinYinTeacherList&py=x',
            '5&PAGENUM=5&urltype=tsites.PinYinTeacherList&py=x',
            '7&PAGENUM=1&urltype=tsites.PinYinTeacherList&py=y',
            '7&PAGENUM=2&urltype=tsites.PinYinTeacherList&py=y',
            '7&PAGENUM=3&urltype=tsites.PinYinTeacherList&py=y',
            '7&PAGENUM=4&urltype=tsites.PinYinTeacherList&py=y',
            '7&PAGENUM=5&urltype=tsites.PinYinTeacherList&py=y',
            '7&PAGENUM=6&urltype=tsites.PinYinTeacherList&py=y',
            '7&PAGENUM=7&urltype=tsites.PinYinTeacherList&py=y',
            '14&PAGENUM=1&urltype=tsites.PinYinTeacherList&py=z',
            '14&PAGENUM=2&urltype=tsites.PinYinTeacherList&py=z',
            '14&PAGENUM=3&urltype=tsites.PinYinTeacherList&py=z',
            '14&PAGENUM=4&urltype=tsites.PinYinTeacherList&py=z',
            '14&PAGENUM=5&urltype=tsites.PinYinTeacherList&py=z',
            '14&PAGENUM=6&urltype=tsites.PinYinTeacherList&py=z',
            '14&PAGENUM=7&urltype=tsites.PinYinTeacherList&py=z',
            '14&PAGENUM=8&urltype=tsites.PinYinTeacherList&py=z',
            '14&PAGENUM=9&urltype=tsites.PinYinTeacherList&py=z',
            '14&PAGENUM=10&urltype=tsites.PinYinTeacherList&py=z',
            '14&PAGENUM=11&urltype=tsites.PinYinTeacherList&py=z',
            '14&PAGENUM=12&urltype=tsites.PinYinTeacherList&py=z',
            '14&PAGENUM=13&urltype=tsites.PinYinTeacherList&py=z',
            '14&PAGENUM=14&urltype=tsites.PinYinTeacherList&py=z',
        ]
        for url in urls:
            yield scrapy.Request(url=header+url+tail, callback=self.parse)

    def parse(self, response):
        urlinfo=response.xpath('//ul[@class="jcrc_list2 clearfix"]/li[@class="fl"]/div[@class="title"]/a/@href').extract()
        for i in urlinfo:
            self.file.write(i+'\n')
        pass